-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 21:34:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Genes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genes` (
  `idGenes` INT NOT NULL,
  `Symbol` VARCHAR(45) NULL,
  `Full_name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Link_sequence` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Protein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Protein` (
  `idProtein` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Molec_function` VARCHAR(45) NULL,
  `Bio_proces` VARCHAR(45) NULL,
  `Sequence` VARCHAR(45) NULL,
  `Proteome` VARCHAR(45) NULL,
  `Genes_idGenes` INT NOT NULL,
  PRIMARY KEY (`idProtein`, `Genes_idGenes`),
  INDEX `fk_Protein_Genes1_idx` (`Genes_idGenes` ASC) VISIBLE,
  CONSTRAINT `fk_Protein_Genes1`
    FOREIGN KEY (`Genes_idGenes`)
    REFERENCES `mydb`.`Genes` (`idGenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Symptoms` (
  `idSymptoms` INT NOT NULL,
  `Pallor` TINYINT NULL,
  `Fatigne` TINYINT NULL,
  `Weakness` TINYINT NULL,
  `Fever` TINYINT NULL,
  `Dizziness` TINYINT NULL,
  `Shortness_breath` TINYINT NULL,
  PRIMARY KEY (`idSymptoms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disease` (
  `idDisease` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `ICD_10` VARCHAR(45) NULL,
  `Protein_idProtein` INT NOT NULL,
  `Symptoms_idSymptoms` INT NOT NULL,
  `Genes_idGenes` INT NOT NULL,
  PRIMARY KEY (`idDisease`, `Protein_idProtein`, `Symptoms_idSymptoms`, `Genes_idGenes`),
  INDEX `fk_Disease_Protein1_idx` (`Protein_idProtein` ASC) VISIBLE,
  INDEX `fk_Disease_Symptoms1_idx` (`Symptoms_idSymptoms` ASC) VISIBLE,
  INDEX `fk_Disease_Genes1_idx` (`Genes_idGenes` ASC) VISIBLE,
  CONSTRAINT `fk_Disease_Protein1`
    FOREIGN KEY (`Protein_idProtein`)
    REFERENCES `mydb`.`Protein` (`idProtein`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disease_Symptoms1`
    FOREIGN KEY (`Symptoms_idSymptoms`)
    REFERENCES `mydb`.`Symptoms` (`idSymptoms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disease_Genes1`
    FOREIGN KEY (`Genes_idGenes`)
    REFERENCES `mydb`.`Genes` (`idGenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
